name: storage_layer
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: 3.4.0+6
  path_provider: 2.0.14
  encrypt: 5.0.1
  crypto: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

