name: interceptor_layer
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 5.2.1+1
  dio_cache_interceptor: 3.4.2
  
  storage_layer:
      path: ../storage_layer
  endpoint_layer:
      path: ../endpoint_layer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
